Add support to cold_standby state
innogames/testtool pull request #20
Opened 2023-06-28 14:07 UTC by lamaral

2024-02-05 18:09 UTC, TuxPowered42 approved these changes

2024-02-06 10:32 UTC, TuxPowered42 requested changes

2024-02-06 10:32 UTC, TuxPowered42 commented on tests/lb_pool_test.cpp
> +TEST_F(LbPoolTest, InitUpDowntimedMaintenance) {
The test name is duplicated.

2024-02-07 09:00 UTC, lamaral commented on tests/lb_pool_test.cpp
> +TEST_F(LbPoolTest, InitUpDowntimedMaintenance) {
That is fixed.

2024-02-07 13:33 UTC, TuxPowered42 approved these changes

2024-02-07 13:34 UTC, merged